[tool.briefcase]
project_name = "Toga Demo"
bundle = "be.weve"
version = "0.0.1"
url = "https://weve.be/togademo"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@weve.be"

[tool.briefcase.app.togademo]
formal_name = "Toga Demo"
description = "Demo with the widgets in Toga"
icon = "src/togademo/resources/togademo"
sources = ['src/togademo']
requires = []


[tool.briefcase.app.togademo.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.togademo.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.togademo.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.togademo.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.togademo.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
